### ISSUE TITLE
Keyboard nav focus disappears

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#168]
For https://github.com/phetsims/QA/issues/244.  Found on Win 8.1 IE with keyboard nav
When tabbing away from the book while it is dragable, the focus disappears then reappears as a solid line.  Edit: Only occurs with the book, not the zoomed in book.  If done in full screen iframe, the keyboard nav does not come back.
Screenshots:
https://drive.google.com/file/d/13G6h9Pa5WmnEvw6_23-9URvGiaX_qn0C/view?usp=sharing

**Comment by zepumph** [comment]
I am I investigated this a bit, and I'm not sure if I have found the root issue yet. I will say though that I saw this sort of behavior on all browsers while developing the `grabDragInteraction`. My best guess is that we are not fully understanding how scenery events work while manually triggering focus and blur 

for example if `document.activeElement`  is the button, and I add `blur` and `focus` event listeners to it, calling `document.activeElement.blur()` and `document.activeElement.focus()` doesn't seem to fire those corresponding scenery listeners.

Furthermore, using `sceneryLog=InputEvent` (on built sim with `--minify.stripLogging=false`) on i.e. found that we aren't getting the focusout events when toggling between the interaction modes (grabbable->draggable & vice versa). We do get that in other browsers, so here is the sceneryLog in i.e.:

```
%c%c[InputEvent] Input.keydownFromBrowser color: #ddd; 
%c%c[InputEvent] Input.keyupFromBrowser color: #ddd; 
%c| %c[InputEvent] Input.focusinFromBrowser color: #ddd; 
%c| %c[InputEvent] Input.focusinFromBrowser color: #ddd; 
```
 whereas here is chrome:
```
[InputEvent] Input.keydownFromBrowser
[InputEvent] Input.keyupFromBrowser
[InputEvent] Input.clickFromBrowser
| [InputEvent] Input.focusoutFromBrowser
| [InputEvent] Input.focusinFromBrowser
| [InputEvent] Input.focusoutFromBrowser
| [InputEvent] Input.focusinFromBrowser
```

That's a substantial number of events that aren't coming through in IE. Oh I also just noticed the click event too.  @jessegreenberg is this surprising to you?

**Comment by jessegreenberg** [comment]
Hmm, that is surprising. I confirmed this is happening on Windows 10 IE11 too.

This is not happening for the draggable magnified book though, pressing tab while that is grabbed correctly sends focus right to the Reset All button. It might be helpful to isolate the difference.

**Comment by jessegreenberg** [comment]
Just confirming that focusout is (reportedly) supported on IE11:
![focusout](https://user-images.githubusercontent.com/6396244/50703582-a2eec400-1022-11e9-8c25-05f66f374486.PNG)

**Comment by jessegreenberg** [comment]
Another hint I just accidentally found - If I remove accessibleOrder in FrictionScreenView, the problem shows up for both the BookNode AND the MagnifierNode.
```js
// controlAreaNode.accessibleOrder = [ resetAllButton ];
```

**Comment by jessegreenberg** [comment]
I tried an HTML page outside of the sim that creates, destroyes, and modifies an HTML element on `focusout`, but IE11 had not problem with the example:
<details>

```html
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8">
<title>Test Page</title>
<body>
  <div id="302-385-634" tabindex="-1">
    <div id="302-385-634-407" aria-label="Movable Chemistry book" role="application" tabindex="0">Movable Chemistry book</div>
    <p id="description-302-385-634-407">Look for grab buttons. Once grabbed, use letter keys W, A, S, or D to move book or zoomed-in book up, left, down, or right.</p>
    <div id="container-302-385-634-445-446-488-490">
      <button id="302-385-634-445-446-488-490">Grab zoomed-in Chemistry book</button>
    </div>
  </div>
</body>
<script type="text/javascript">
  var div1 = document.getElementById( '302-385-634-407' );
  var parent1 = document.getElementById( '302-385-634' );
  var referenceNode = document.getElementById( 'description-302-385-634-407' );
  parent1.addEventListener( 'focusout', function( event ) {
    console.log( 'focusout' );
    div1.tabindex = "-1";

    parent1.removeChild( div1 );

    div1 = document.createElement( 'button' );
    div1.id = '302-385-634-407';
    div1.innerHTML = 'Grabbable Chemistry book';

    var parentContainer = document.createElement( 'div' );
    parentContainer.insertBefore( div1, null );

    parent1.insertBefore( parentContainer, referenceNode )
  } );
  parent1.addEventListener( 'focusin', function( event ) {
    console.log( 'focusin' );
  } );
</script>
```

**Comment by zepumph** [comment]
Yesterday @jessegreenberg and I logged quite a bit yesterday to get some understanding, but nothing too substantial:

From startup
tab to macro book
space to grab it
tab to make the focus disappear
tab again to highlight the macro book again

yielded a log like
```
%c%c[InputEvent] Input.focusinFromBrowser color: #ddd; 
event target:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
active element:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
%c%c[InputEvent] Input.keydownFromBrowser color: #ddd; 
event target:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
active element:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
%c%c[InputEvent] Input.keyupFromBrowser color: #ddd; 
event target:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
active element:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
%c%c[InputEvent] Input.clickFromBrowser color: #ddd; 
event target:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
active element:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
beforeMutate false
beforeof before blur
%c| %c[InputEvent] Input.focusoutFromBrowser color: #ddd; 
event target:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418" aria-roledescription="Movable Chemistry book">Grab Chemistry book</button>
active element:
<body style="margin: 0px; padding: 0px; overflow: hidden; background-color: black;"></body>
beforeof after blur
afterof before focus
%c| %c[InputEvent] Input.focusinFromBrowser color: #ddd; 
event target:
<div tabindex="0" id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418" aria-roledescription="Movable Chemistry book">Grab Chemistry book</div>
active element:
<div tabindex="0" id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418" aria-roledescription="Movable Chemistry book">Grab Chemistry book</div>
afterof before blur
beforeof before blur
%c| %c[InputEvent] Input.focusoutFromBrowser color: #ddd; 
event target:
<div tabindex="0" id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418" aria-roledescription="Movable Chemistry book">Grab Chemistry book</div>
active element:
<body style="margin: 0px; padding: 0px; overflow: hidden; background-color: black;"></body>
beforeof after blur
afterof before focus
%c| %c[InputEvent] Input.focusinFromBrowser color: #ddd; 
event target:
<div tabindex="0" id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418" aria-roledescription="Movable Chemistry book">Grab Chemistry book</div>
active element:
<div tabindex="0" id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418" aria-roledescription="Movable Chemistry book">Grab Chemistry book</div>
afterof before blur
afterMutate false
%c%c[InputEvent] Input.keydownFromBrowser color: #ddd; 
event target:
<div tabindex="0" id="332-396-659-418" role="application" aria-label="Movable Chemistry book" data-focusable="true" data-trail-id="332-396-659-418" aria-roledescription="Movable Chemistry book">Movable Chemistry book</div>
active element:
<div tabindex="0" id="332-396-659-418" role="application" aria-label="Movable Chemistry book" data-focusable="true" data-trail-id="332-396-659-418" aria-roledescription="Movable Chemistry book">Movable Chemistry book</div>
%c%c[InputEvent] Input.focusoutFromBrowser color: #ddd; 
event target:
<div tabindex="0" id="332-396-659-418" role="application" aria-label="Movable Chemistry book" data-focusable="true" data-trail-id="332-396-659-418" aria-roledescription="Movable Chemistry book">Movable Chemistry book</div>
active element:
<button id="332-396-659-463-464-506-508" data-focusable="true" data-trail-id="332-396-659-463-464-506-508">Grab zoomed-in Chemistry book</button>
beforeMutate true
beforeof before blur
beforeof after blur
afterof before focus
afterof before blur
beforeof before blur
beforeof after blur
afterof before focus
afterof before blur
afterMutate true
%c%c[InputEvent] Input.focusinFromBrowser color: #ddd; 
event target:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
active element:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
%c%c[InputEvent] Input.keyupFromBrowser color: #ddd; 
event target:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
active element:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
%c%c[InputEvent] Input.keydownFromBrowser color: #ddd; 
event target:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
active element:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
%c%c[InputEvent] Input.focusoutFromBrowser color: #ddd; 
event target:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
active element:
<button id="332-396-659-418" data-focusable="true" data-trail-id="332-396-659-418">Grab Chemistry book</button>
```


And here is a patch with all the logging 

<details>
Index: scenery/js/accessibility/AccessibilityUtil.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/accessibility/AccessibilityUtil.js	(revision c3c56b71381950a9a30829e0490d6f82c704131f)
+++ scenery/js/accessibility/AccessibilityUtil.js	(date 1546987998701)
@@ -375,7 +375,9 @@
         var childToRemove = childrenToRemove[ i ];
 
         assert && assert( element.contains( childToRemove ), 'element does not contain child to be removed: ', childToRemove );
-
+        if ( childToRemove === document.activeElement ) {
+          childToRemove.blur();
+        }
         element.removeChild( childToRemove );
       }
 
Index: scenery/js/input/Input.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/input/Input.js	(revision c3c56b71381950a9a30829e0490d6f82c704131f)
+++ scenery/js/input/Input.js	(date 1546987998685)
@@ -757,7 +757,11 @@
 
           // These exist for the lifetime of the display, and need not be disposed.
           this.display.accessibleDOMElement.addEventListener( eventName, event => {
-            sceneryLog && sceneryLog.InputEvent && sceneryLog.InputEvent( `Input.${eventName}FromBrowser` );
+            sceneryLog && sceneryLog.InputEvent && sceneryLog.InputEvent( `Input.${eventName}FromBrowser`, );
+            console.log( 'event target:' );
+            console.log( event.target );
+            console.log( 'active element:' );
+            console.log( document.activeElement );
             sceneryLog && sceneryLog.InputEvent && sceneryLog.push();
 
             // Create the a11yPointer lazily
Index: scenery/js/accessibility/AccessibilityTree.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/accessibility/AccessibilityTree.js	(revision c3c56b71381950a9a30829e0490d6f82c704131f)
+++ scenery/js/accessibility/AccessibilityTree.js	(date 1546987998709)
@@ -398,6 +398,11 @@
     beforeOp: function() {
       // paranoia about initialization order (should be safe)
       focusedNode = scenery.Display && scenery.Display.focusedNode;
+
+      // for consistency
+      console.log( 'beforeof before blur' );
+      focusedNode && focusedNode.blur();
+      console.log( 'beforeof after blur' );
     },
 
     /**
@@ -405,7 +410,10 @@
      * @private
      */
     afterOp: function() {
+      console.log( 'afterof before focus' );
+
       focusedNode && focusedNode.focus();
+      console.log( 'afterof before blur' );
     },
 
     /**
Index: scenery-phet/js/accessibility/GrabDragInteraction.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery-phet/js/accessibility/GrabDragInteraction.js	(revision f64c041d3ad0b05ed088c81d59acaa6aa6b2773d)
+++ scenery-phet/js/accessibility/GrabDragInteraction.js	(date 1546894624427)
@@ -229,7 +229,7 @@
 
             this.turnToDraggable();
 
-            this.node.focus();
+            // this.node.focus();
 
             this.onGrab();
 
@@ -385,8 +385,10 @@
       // remove all previous listeners from the node
       this.removeInputListeners( listenersToRemove );
 
+      console.log( `beforeMutate ${this.grabbable}` );
       // update the PDOM of the node
       this.node.mutate( optionsToMutate );
+      console.log( `afterMutate ${this.grabbable}` );
 
       this.addInputListeners( listenersToAdd );
 

</details>

**Comment by zepumph** [comment]
While working on this more today, we have found:

* The following code will break both the macro and magnified views:
```
    const playAreaNode = new PlayAreaNode();
    this.addChild( playAreaNode );

    const blarg = new RoundPushButton();
    this.addChild( blarg );

    const blarg2 = new RoundPushButton();
    this.addChild( blarg2 );

    // a11y
    playAreaNode.accessibleOrder = [ blarg, chemistryBookNode, this.magnifierNode, blarg2 ];

```

This is because `blarg2` is last instead of one of the chemistry books.

* Commenting out this accessibleOrder line made the issue show up in both books also, as told in https://github.com/phetsims/friction/issues/168#issuecomment-452166675

* Switching the order of the books will swap which book the bug occurs on, always on the last book in the a11y order.

**Comment by zepumph** [comment]
<details>

```

Index: scenery/js/accessibility/AccessibilityUtil.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/accessibility/AccessibilityUtil.js	(revision 6ab6d1cc337b8e5bf7969c989d7b81c4c5951f4d)
+++ scenery/js/accessibility/AccessibilityUtil.js	(date 1547505581526)
@@ -375,7 +375,9 @@
         var childToRemove = childrenToRemove[ i ];
 
         assert && assert( element.contains( childToRemove ), 'element does not contain child to be removed: ', childToRemove );
-
+        if ( childToRemove === document.activeElement ) {
+          childToRemove.blur();
+        }
         element.removeChild( childToRemove );
       }
 
@@ -391,10 +393,30 @@
      */
     insertElements: function( element, childrenToAdd, beforeThisElement ) {
 
+      // TODO: this is only called nested under AccesssibilityTree.beforeOp(), so we probably don't need this
+      var previousFocused = null;
+
+      for ( let i = 0; i < childrenToAdd.length; i++ ) {
+        const childToAdd = childrenToAdd[ i ];
+        if ( document.activeElement === childToAdd ) {
+          console.log( 'we are bluring before insertBefore');
+          previousFocused = childToAdd;
+          childToAdd.blur();
+        }
+      }
+
+      if ( document.activeElement === element ) {
+        console.log( 'we are bluring before insertBefore');
+        previousFocused = element;
+        element.blur();
+      }
+
       for ( var i = 0; i < childrenToAdd.length; i++ ) {
         var childToAdd = childrenToAdd[ i ];
         element.insertBefore( childToAdd, beforeThisElement || null );
       }
+
+      previousFocused && previousFocused.focus();
     },
 
     /**
Index: scenery/js/input/Input.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/input/Input.js	(revision 6ab6d1cc337b8e5bf7969c989d7b81c4c5951f4d)
+++ scenery/js/input/Input.js	(date 1547505179434)
@@ -757,7 +757,11 @@
 
           // These exist for the lifetime of the display, and need not be disposed.
           this.display.accessibleDOMElement.addEventListener( eventName, event => {
-            sceneryLog && sceneryLog.InputEvent && sceneryLog.InputEvent( `Input.${eventName}FromBrowser` );
+            sceneryLog && sceneryLog.InputEvent && sceneryLog.InputEvent( `Input.${eventName}FromBrowser`, );
+            console.log( 'event target:' );
+            console.log( event.target );
+            console.log( 'active element:' );
+            console.log( document.activeElement );
             sceneryLog && sceneryLog.InputEvent && sceneryLog.push();
 
             // Create the a11yPointer lazily
Index: scenery/js/accessibility/AccessibilityTree.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/accessibility/AccessibilityTree.js	(revision 6ab6d1cc337b8e5bf7969c989d7b81c4c5951f4d)
+++ scenery/js/accessibility/AccessibilityTree.js	(date 1547500515205)
@@ -398,6 +398,24 @@
     beforeOp: function() {
       // paranoia about initialization order (should be safe)
       focusedNode = scenery.Display && scenery.Display.focusedNode;
+
+      console.log( '\n' );
+      if ( focusedNode ) {
+        console.log( 'focusedNode:' );
+        console.log( focusedNode.accessibleInstances[ 0 ].peer.primarySibling );
+      }
+      else {
+        console.log( 'focusedNode: falsey' );
+      }
+
+      console.log( 'activeElement:' );
+      console.log( document.activeElement );
+      console.log( '\n' );
+
+      // for consistency
+      console.log( 'beforeop before blur' );
+      focusedNode && focusedNode.blur();
+      console.log( 'beforeop after blur' );
     },
 
     /**
@@ -405,7 +423,10 @@
      * @private
      */
     afterOp: function() {
+      console.log( 'afterop before focus' );
+
       focusedNode && focusedNode.focus();
+      console.log( 'afterop before blur' );
     },
 
     /**
Index: scenery/js/display/Display.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/display/Display.js	(revision 6ab6d1cc337b8e5bf7969c989d7b81c4c5951f4d)
+++ scenery/js/display/Display.js	(date 1547500819816)
@@ -59,6 +59,7 @@
   var escapeHTML = require( 'PHET_CORE/escapeHTML' );
   var Events = require( 'AXON/Events' );
   var extend = require( 'PHET_CORE/extend' );
+  var Focus = require( 'SCENERY/accessibility/Focus' );
   var inherit = require( 'PHET_CORE/inherit' );
   var KeyStateTracker = require( 'SCENERY/accessibility/KeyStateTracker' );
   var Matrix3 = require( 'DOT/Matrix3' );
@@ -1688,6 +1689,7 @@
      * @param  {Focus|null} value
      */
     set focus( value ) {
+      assert && assert( value instanceof Focus || value === null, 'incorrect type for value: ' + value );
 
       // If in phet-io brand, a11y is enabled, and the focus is not null
       if ( window.phet && phet.phetio && phet.chipper.accessibility && value ) {
Index: scenery/js/overlays/FocusOverlay.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/overlays/FocusOverlay.js	(revision 6ab6d1cc337b8e5bf7969c989d7b81c4c5951f4d)
+++ scenery/js/overlays/FocusOverlay.js	(date 1547501955006)
@@ -367,7 +367,10 @@
       this.boundsFocusHighlightPath.setShapeFromNode( this.node );
     },
 
-    // Called when the main Scenery focus pair (Display,Trail) changes.
+    /**
+     * Called when the main Scenery focus pair (Display,Trail) changes.
+     * @param {Focus} focus
+     */
     onFocusChange: function( focus ) {
       var newTrail = ( focus && focus.display === this.display ) ? focus.trail : null;
 
Index: scenery/js/accessibility/AccessiblePeer.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/accessibility/AccessiblePeer.js	(revision 6ab6d1cc337b8e5bf7969c989d7b81c4c5951f4d)
+++ scenery/js/accessibility/AccessiblePeer.js	(date 1547500819826)
@@ -690,6 +690,8 @@
     blur: function() {
       assert && assert( this._primarySibling, 'must have a primary sibling to blur' );
 
+      // TODO: why the heck no setting the Display focus to null?!?!?!
+
       // no op if primary sibling does not have focus
       if ( document.activeElement === this._primarySibling ) {
 
Index: joist/js/PhetMenu.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- joist/js/PhetMenu.js	(revision 2fbde2d5aebfcd02f4d1cf0afba58d52c0e03190)
+++ joist/js/PhetMenu.js	(date 1547500819833)
@@ -468,8 +468,9 @@
     show: function() {
       if ( !this.isShowing ) {
 
+        // TODO: why not null? are we sure blur is happening correctly
         // make sure that any previously focused elements no longer have focus
-        Display.focus = false;
+        Display.focus = null;
 
         window.phet.joist.sim.showPopup( this, true );
         this.isShowing = true;
Index: friction/js/friction/view/FrictionScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- friction/js/friction/view/FrictionScreenView.js	(revision 32c5da14ef06d5ec2e87ec4e4273e438554585ae)
+++ friction/js/friction/view/FrictionScreenView.js	(date 1547503594042)
Index: scenery-phet/js/accessibility/GrabDragInteraction.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery-phet/js/accessibility/GrabDragInteraction.js	(revision f65f46f07c7533cb5eda69479c236e4f56b9a5d3)
+++ scenery-phet/js/accessibility/GrabDragInteraction.js	(date 1547498829041)
@@ -229,7 +229,7 @@
 
             this.turnToDraggable();
 
-            this.node.focus();
+            // this.node.focus();
 
             this.onGrab();
 
@@ -385,8 +385,10 @@
       // remove all previous listeners from the node
       this.removeInputListeners( listenersToRemove );
 
+      console.log( `beforeMutate ${this.grabbable}` );
       // update the PDOM of the node
       this.node.mutate( optionsToMutate );
+      console.log( `afterMutate ${this.grabbable}` );
 
       this.addInputListeners( listenersToAdd );
 

```

</details>

**Comment by jessegreenberg** [comment]
@zepumph and I found a workaround today! We started https://github.com/phetsims/scenery/issues/925 and will commit a fix that we tested works well in Friction. The rest of that issue will be to see if we can get better consistency of events in IE11 so this doesn't happen again.

**Comment by jessegreenberg** [comment]
OK @zepumph, https://github.com/phetsims/scenery/commit/ed86a2f54f5dc38b9650d4e581dd50b96d777f67 should be the commit to grab.

**Comment by emily-phet** [comment]
That's great to hear!

**Comment by terracoda** [comment]
Wonderful work on this @zepumph and @jessegreenberg.

In reference to this comment from @jessegreenberg...
> So it seems like destroying DOM elements (like when we change tagName) doesn't trigger focusOut in IE11, but calling blur() does. But this didn't fix the issue.

... are there times when an element that actually has focus is being destroyed? It would be my intuition that if an element that has focus is to be removed from the PDOM, that we would have to move focus first before removing it. If not, it seems that focus could easily get lost.

I think you are already aware of this based on your comment above.

**Comment by zepumph** [comment]
Commit has been cherry-picked into branch (note to self)

**Comment by KatieWoe** [comment]
Seems fixed 1.5.0-rc.2

**Comment by kellywurtz** [comment]
Occured on rc.2 (MacOS 10.14.2, Safari only).

**Comment by jessegreenberg** [comment]
@KatieWoe or @kellywurtz can you please test to see if this was also present in MacOS 10.14.2 for rc.1? https://phet-dev.colorado.edu/html/friction/1.5.0-rc.1/phet/friction_en_phet.html

**Comment by kellywurtz** [comment]
Yes, also present on rc.1.

**Comment by KatieWoe** [comment]
Happens on Mac 10.13.6 safari as well

**Comment by zepumph** [comment]
Our workaround has a specific ie11 check wrapped around it, so it would make sense that this bug wouldn't be fixed in any other system. @jessegreenberg should we just add the check on safari too? Honestly I'm not too happy about this, and it seems like a drag to expand the workaround.

**Comment by zepumph** [comment]
Fix pushed to master. Will you test that this has fixed it @KatieWoe?

**Comment by KatieWoe** [comment]
Still happening on master

**Comment by jessegreenberg** [comment]
On Slack @KatieWoe said that this was still broken in safari 12.0.3. It looks like our safari checks in platform.js only go up to safari11, which could explain why the fix didn't work in that test. We should add safari 12 to platform.js.

**Comment by jessegreenberg** [comment]
Scratch that, there is no *specific* check for safari 12 in platform.js, but the general check for safari doesn't include version number
```js
    // Whether the browser matches any version of safari, including mobile
    safari: isMobileSafari() || !!( ua.match( /Version\// ) && ua.match( /Safari\// ) && ua.match( /AppleWebKit/ ) ),
```

**Comment by jessegreenberg** [comment]
Not on hand, I might be able to borrow one.

**Comment by jessegreenberg** [comment]
Yep, I can borrow one tomorrow! Ill take a look.

**Comment by zepumph** [comment]
Though I'm not working tomorrow. If you still have it during normal working hours, I'd love to tag along. (ping me and we'll see).

**Comment by zepumph** [comment]
In https://github.com/phetsims/scenery/issues/925 @jessegreenberg dove in and discovered the root problem, and a decent solution that we like moving forward. 

He also found that the reason why safari isn't fixed by our workaround, see https://github.com/phetsims/scenery/issues/925#issuecomment-460016658

To proceed with friction, we both think it is best to just cherrypick the snippet from the comment above into the rc branch:

`          if ( ( platform.ie11 || platform.safari ) && ( targetInDisplay ) ) {` 

where we don't check on `document.activeElement`.

I will add that to the branch and we will proceed with the next RC.

**Comment by zepumph** [comment]
In https://github.com/phetsims/scenery/issues/925 @jessegreenberg dove in and discovered the root problem, and a decent solution that we like moving forward. 

He also found that the reason why safari isn't fixed by our workaround, see https://github.com/phetsims/scenery/issues/925#issuecomment-460016658

To proceed with friction, we both think it is best to just cherrypick the snippet from the comment above into the rc branch:

`          if ( ( platform.ie11 || platform.safari ) && ( targetInDisplay ) ) {` 

where we don't check on `document.activeElement`.

I will add that to the branch and we will proceed with the next RC.

**Comment by zepumph** [comment]
Cherry picked into 1.5 branch above.

**Comment by KatieWoe** [comment]
I'm still seeing this in 1.5.0-rc.3.  Since it only happens on the first book, it may not be worth pursuing any more.  Up to you though.  Removing tag as not fixed.

**Comment by zepumph** [comment]
Ugh. Thanks @KatieWoe. Tagging @jessegreenberg so he can review https://github.com/phetsims/scenery/commit/deac1943c40373ad36454259dc82d02bc9b4ae23 to make sure it looks like what we talked about. I guess the only thing to do next would be to push all the changes you worked on earlier this week.

**Comment by jessegreenberg** [comment]
Shoot, so sorry for the hassle @zepumph, I was sure I tested https://github.com/phetsims/scenery/commit/deac1943c40373ad36454259dc82d02bc9b4ae23 in Safari, perhaps I missed something when I copied it into https://github.com/phetsims/scenery/issues/925#issuecomment-460016658. Ill take a look.

**Comment by jessegreenberg** [comment]
Just adding a reference to https://github.com/phetsims/QA/issues/282.

**Comment by jessegreenberg** [comment]
I am wondering if https://github.com/phetsims/scenery/commit/deac1943c40373ad36454259dc82d02bc9b4ae23 just wasn't added to friction's 1.5 dependencies.json? I don't see the change when I run grunt checkout-shas of 1.5.

**Comment by zepumph** [comment]
Oh shoot! I'm sorry! I'll make another RC and just have a spot check in this issue.

**Comment by jessegreenberg** [comment]
No worries! I updated the SHA in https://github.com/phetsims/friction/commit/ce2014b62f3a7aea3b4053d227a8f40d8dd19e01. But I also noticed a difference between this and https://github.com/phetsims/scenery/issues/925#issuecomment-460016658. In the scenery comment `activeElement` var pointed to event.relatedTarget rather than document.activeElement.

**Comment by zepumph** [comment]
Again you are right. I will make the change.

**Comment by jessegreenberg** [comment]
> I'll make another RC and just have a spot check in this issue.

Great, thanks!

**Comment by zepumph** [comment]
@KatieWoe are things fixed in this version?

https://github.com/phetsims/friction/issues/168

**Comment by KatieWoe** [comment]
@zepumph Checked on safari and IE.  The described problem seems fixed.  However, I saw a very odd problem on safari.  Normally, if you grab the book (dotted outline) and tab away it drops the book as you do so.  If you focus back on it there will be a solid line and you have to pick it up again.  Now, at least on safari, if you tab away while the book is picked up, it does not drop.  If you focus back on it there will be a dotted line.

**Comment by zepumph** [comment]
@jessegreenberg and I fixed this this morning and tested on safari in two different ways (on my mac osx 10.9 and on macincloud). @KatieWoe can you give a spot check to this as well, just to be sure.

https://phet-dev.colorado.edu/html/friction/1.5.0-rc.6/phet/friction_all_phet.html

**Comment by KatieWoe** [comment]
Looks good on master safari

**Comment by jessegreenberg** [comment]
Verified as fixed and sim was deployed so this can now be closed!
